-- Fixture de teste -- reproduz a forma de `rfb_atos.*` na nuvem (ratio).
--
-- NAO e a DDL canonica. A canonica e a 004/005 (esqueleto) + 006 (modelo rico),
-- que rodaram na nuvem. Este arquivo existe para que auditar_cobertura.py e a
-- migration 010 possam ser exercitados contra um Postgres real em CI/local, sem
-- tunnel SSM e sem tocar em producao.
--
-- Colunas espelhadas de: td-creditos/migrations/006_rfb_atos_rico.sql e das
-- listas de INSERT de td-rfb-atos/scripts/migrate_to_cloud.py (fonte de verdade
-- dos nomes reais das colunas).
--
-- Diferenca deliberada: `ato_materia.embedding` aqui e TEXT, nao halfvec(3072) --
-- a extensao pgvector nao e necessaria para nada que auditamos (so testamos
-- `embedding IS NULL`). Se o teste passar a depender de operacao vetorial, este
-- fixture precisa de pgvector.

CREATE SCHEMA IF NOT EXISTS rfb_atos;
SET search_path = rfb_atos, public;

CREATE TABLE rfb_atos.ato (
    id                    INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    tipo_ato              TEXT NOT NULL,
    numero                TEXT,
    ano                   INTEGER,
    -- coluna GERADA na nuvem (pg_get_expr conferido em 13/09/2026): INSERT não pode informá-la
    identificador         TEXT GENERATED ALWAYS AS
                          ((((tipo_ato || ' ') || numero) || '/') || (ano)::text) STORED,
    importado_em          TIMESTAMPTZ,   -- da 004, conferido na nuvem em 13/09/2026
    emissor               TEXT,
    data_publicacao       DATE,
    data_vigencia_inicio  DATE,
    data_vigencia_fim     DATE,
    eficacia_atual        TEXT,
    ementa                TEXT,
    url_pdf               TEXT,
    url_html              TEXT,
    metadados             JSONB,
    importado_de          TEXT,
    criado_em             TIMESTAMPTZ NOT NULL DEFAULT now(),
    atualizado_em         TIMESTAMPTZ NOT NULL DEFAULT now(),
    -- colunas da 006
    status_vigencia       TEXT,
    link                  TEXT,
    pdf_disponivel        BOOLEAN DEFAULT FALSE,
    content_disponivel    BOOLEAN DEFAULT FALSE,
    analise_completa      BOOLEAN DEFAULT FALSE,
    fonte_origem          TEXT,
    ato_legacy_id         INTEGER,
    legacy_table          TEXT,
    id_portal             INTEGER,
    CONSTRAINT ato_chave_natural UNIQUE (tipo_ato, numero, emissor, data_publicacao)
);

CREATE TABLE rfb_atos.ato_content (
    ato_id              INTEGER PRIMARY KEY REFERENCES rfb_atos.ato(id) ON DELETE CASCADE,
    texto_completo      TEXT,
    origem_extracao     TEXT,
    processed_at        TIMESTAMPTZ DEFAULT now(),
    fonte_extracao      TEXT,
    caracteres          INTEGER,
    paginas             INTEGER,
    tipo_versao         TEXT DEFAULT 'vigente',
    id_arquivo_binario  INTEGER,
    pdf_path            TEXT
);

CREATE TABLE rfb_atos.ato_materia (
    id                    INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    ato_id                INTEGER NOT NULL REFERENCES rfb_atos.ato(id) ON DELETE CASCADE,
    ordem                 INTEGER NOT NULL,
    -- colunas da 004 (esqueleto), conferidas na nuvem em 13/09/2026
    tributos              TEXT[],
    regimes               TEXT[],
    setores               TEXT[],
    trecho_canonico       TEXT,
    natureza              TEXT,
    tema_macro            TEXT,
    tema_especifico       TEXT,
    subtema               TEXT,
    tags                  TEXT[] DEFAULT '{}',
    ementa_trecho         TEXT,
    tese_contribuinte     TEXT,
    tese_fazenda          TEXT,
    tese_adotada          TEXT,
    resultado             TEXT,
    fato_consultado       TEXT,
    solucao               TEXT,
    fundamentacao_resumo  TEXT,
    metadata_tematico     JSONB,
    posicionamento        TEXT,
    sinal                 TEXT,
    sinal_classified_at   TIMESTAMPTZ,
    sinal_model           TEXT,
    embedding             TEXT,          -- halfvec(3072) na nuvem; ver cabecalho
    embedding_source      TEXT,
    embedded_at           TIMESTAMPTZ,
    llm_model             TEXT,
    llm_processed_at      TIMESTAMPTZ,
    schema_version        TEXT DEFAULT 'v1',
    CONSTRAINT ato_materia_sinal_check
        CHECK (sinal IS NULL OR sinal IN ('AUTORIZA','VEDA','CONDICIONA','INDETERMINADO')),
    CONSTRAINT ato_materia_ato_id_ordem_key UNIQUE (ato_id, ordem)
);

CREATE INDEX ix_materia_ato ON rfb_atos.ato_materia(ato_id);

-- Tabelas-filhas da materia, como na 006 do td-creditos (rodou na nuvem).
CREATE TABLE rfb_atos.materia_tributo (
    materia_id     INTEGER NOT NULL REFERENCES rfb_atos.ato_materia(id) ON DELETE CASCADE,
    tributo_codigo TEXT    NOT NULL,
    regime         TEXT,
    codigo_receita TEXT
);
CREATE UNIQUE INDEX materia_tributo_uq
    ON rfb_atos.materia_tributo (materia_id, tributo_codigo, COALESCE(regime, 'NULL_REGIME'));

CREATE TABLE rfb_atos.materia_cnae (
    materia_id  INTEGER NOT NULL REFERENCES rfb_atos.ato_materia(id) ON DELETE CASCADE,
    cnae_codigo TEXT    NOT NULL,
    descricao   TEXT,
    relevancia  TEXT,
    confianca   TEXT,
    PRIMARY KEY (materia_id, cnae_codigo)
);

CREATE TABLE rfb_atos.materia_dispositivo (
    id             BIGSERIAL PRIMARY KEY,
    materia_id     INTEGER REFERENCES rfb_atos.ato_materia(id) ON DELETE CASCADE,
    tipo_norma     TEXT,
    referencia     TEXT,
    dispositivo    TEXT,
    texto_resumido TEXT,
    tipo_uso       TEXT DEFAULT 'fundamento'
);

-- Espelhadas do schema real da nuvem (conferido em 13/09/2026) para a migration 011
-- e o carregador de JSON do portal poderem ser exercitados.

CREATE TABLE rfb_atos.ato_relacao (
    id                  INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    ato_origem_id       INTEGER NOT NULL REFERENCES rfb_atos.ato(id) ON DELETE CASCADE,
    ato_destino_id      INTEGER REFERENCES rfb_atos.ato(id) ON DELETE SET NULL,
    destino_externo     TEXT,
    tipo_relacao        TEXT NOT NULL,
    trecho_referencia   TEXT,
    criado_em           TIMESTAMPTZ NOT NULL DEFAULT now(),
    data_relacao        DATE,
    data_efeito         DATE,
    parcial             BOOLEAN DEFAULT FALSE,
    observacao          TEXT,
    fonte               TEXT,
    dispositivo_afetado TEXT,
    CONSTRAINT ato_relacao_unica UNIQUE (ato_origem_id, ato_destino_id, tipo_relacao)
);

CREATE TABLE rfb_atos.ato_segmento (
    ato_id            INTEGER NOT NULL REFERENCES rfb_atos.ato(id) ON DELETE CASCADE,
    id_segmento       BIGINT  NOT NULL,
    versao_segmento   INTEGER NOT NULL DEFAULT 1,
    ordem             INTEGER,
    id_tipo_segmento  INTEGER,
    id_assunto        INTEGER,
    texto_integra     TEXT,
    is_original       BOOLEAN DEFAULT FALSE,
    is_compilado      BOOLEAN DEFAULT FALSE,
    is_tachado        BOOLEAN DEFAULT FALSE,
    is_omitido        BOOLEAN DEFAULT FALSE,
    is_agendado       BOOLEAN DEFAULT FALSE,
    raw               JSONB,
    criado_em         TIMESTAMPTZ NOT NULL DEFAULT now(),
    PRIMARY KEY (ato_id, id_segmento, versao_segmento)
);

CREATE TABLE rfb_atos.ato_alteracao_historico (
    id                         INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    ato_alvo_id                INTEGER NOT NULL REFERENCES rfb_atos.ato(id) ON DELETE CASCADE,
    id_segmento_alvo           BIGINT  NOT NULL,
    ato_modificador_id         INTEGER REFERENCES rfb_atos.ato(id),
    id_ato_modificador_portal  INTEGER NOT NULL,
    data_inicio_vigencia       DATE,
    data_republicacao          DATE,
    texto_anotacao             TEXT,
    raw_anotacao_id            INTEGER,
    eh_agendamento             BOOLEAN DEFAULT FALSE,
    texto_agendamento          TEXT,
    criado_em                  TIMESTAMPTZ NOT NULL DEFAULT now(),
    CONSTRAINT alteracao_uq UNIQUE (ato_alvo_id, id_segmento_alvo, raw_anotacao_id)
);
