-- Fixture de teste -- reproduz a forma de `rfb_atos.*` na nuvem (ratio).
--
-- NAO e a DDL canonica. A canonica e a 004/005 (esqueleto) + 006 (modelo rico),
-- que rodaram na nuvem. Este arquivo existe para que auditar_cobertura.py e a
-- migration 010 possam ser exercitados contra um Postgres real em CI/local, sem
-- tunnel SSM e sem tocar em producao.
--
-- Colunas espelhadas de: td-creditos/migrations/006_rfb_atos_rico.sql e das
-- listas de INSERT de td-rfb-atos/scripts/migrate_to_cloud.py (fonte de verdade
-- dos nomes reais das colunas).
--
-- Diferenca deliberada: `ato_materia.embedding` aqui e TEXT, nao halfvec(3072) --
-- a extensao pgvector nao e necessaria para nada que auditamos (so testamos
-- `embedding IS NULL`). Se o teste passar a depender de operacao vetorial, este
-- fixture precisa de pgvector.

CREATE SCHEMA IF NOT EXISTS rfb_atos;
SET search_path = rfb_atos, public;

CREATE TABLE rfb_atos.ato (
    id                    INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    tipo_ato              TEXT NOT NULL,
    numero                TEXT,
    ano                   INTEGER,
    emissor               TEXT,
    data_publicacao       DATE,
    data_vigencia_inicio  DATE,
    data_vigencia_fim     DATE,
    eficacia_atual        TEXT,
    ementa                TEXT,
    url_pdf               TEXT,
    url_html              TEXT,
    metadados             JSONB,
    importado_de          TEXT,
    criado_em             TIMESTAMPTZ NOT NULL DEFAULT now(),
    atualizado_em         TIMESTAMPTZ NOT NULL DEFAULT now(),
    -- colunas da 006
    status_vigencia       TEXT,
    link                  TEXT,
    pdf_disponivel        BOOLEAN DEFAULT FALSE,
    content_disponivel    BOOLEAN DEFAULT FALSE,
    analise_completa      BOOLEAN DEFAULT FALSE,
    fonte_origem          TEXT,
    ato_legacy_id         INTEGER,
    legacy_table          TEXT,
    id_portal             INTEGER,
    CONSTRAINT ato_chave_natural UNIQUE (tipo_ato, numero, emissor, data_publicacao)
);

CREATE TABLE rfb_atos.ato_content (
    ato_id              INTEGER PRIMARY KEY REFERENCES rfb_atos.ato(id) ON DELETE CASCADE,
    texto_completo      TEXT,
    origem_extracao     TEXT,
    processed_at        TIMESTAMPTZ DEFAULT now(),
    fonte_extracao      TEXT,
    caracteres          INTEGER,
    paginas             INTEGER,
    tipo_versao         TEXT DEFAULT 'vigente',
    id_arquivo_binario  INTEGER,
    pdf_path            TEXT
);

CREATE TABLE rfb_atos.ato_materia (
    id                    INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    ato_id                INTEGER NOT NULL REFERENCES rfb_atos.ato(id) ON DELETE CASCADE,
    ordem                 INTEGER,
    natureza              TEXT,
    tema_macro            TEXT,
    tema_especifico       TEXT,
    subtema               TEXT,
    tags                  TEXT[] DEFAULT '{}',
    ementa_trecho         TEXT,
    tese_contribuinte     TEXT,
    tese_fazenda          TEXT,
    tese_adotada          TEXT,
    resultado             TEXT,
    fato_consultado       TEXT,
    solucao               TEXT,
    fundamentacao_resumo  TEXT,
    metadata_tematico     JSONB,
    posicionamento        TEXT,
    sinal                 TEXT,
    sinal_classified_at   TIMESTAMPTZ,
    sinal_model           TEXT,
    embedding             TEXT,          -- halfvec(3072) na nuvem; ver cabecalho
    embedding_source      TEXT,
    embedded_at           TIMESTAMPTZ,
    llm_model             TEXT,
    llm_processed_at      TIMESTAMPTZ,
    schema_version        TEXT DEFAULT 'v1',
    CONSTRAINT ato_materia_sinal_check
        CHECK (sinal IS NULL OR sinal IN ('AUTORIZA','VEDA','CONDICIONA','INDETERMINADO'))
);

CREATE INDEX ix_materia_ato ON rfb_atos.ato_materia(ato_id);
